### ISSUE TITLE
Campaign - Missing the status for item campaign

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#74]
1. ![Image](https://user-images.githubusercontent.com/44457418/179468295-2a861629-4f67-45a1-bb2a-1e8d3a010669.png)
2. Screen has flash when user click on the Campaign name
3. After click the Campaign name the icon + change to - => (the +/- has only when user click on +/- icon, the name just only for edit)
http://recordit.co/C6N7dFwTuD

**Comment by GiaPhu811** [comment]
Cannot get content when click expand a @nguyenvuledu

**Comment by anhtuan2588** [comment]
1. This 'status' was returned from the API ('published' parameter), using this for frontend status @GiaPhu811

**Comment by toanredweb** [comment]
I don't see a return from the API (parameter 'published') , pls help me check again . Thanks a @anhtuan2588

**Comment by CongThuong** [comment]
This 'status' was returned from the API ('published' parameter), using this for frontend status. Please check again Em @GiaPhu811

**Comment by toanredweb** [comment]
Im checking a @CongThuong

**Comment by NguyenTrang091296** [comment]
We have 3 status for campaigns:
Running: publish = 1: The current date is included in the start date - end date
Stop: publish = 0: The current date is greater than the start date
Schedule: publish = 2: The current date is less than the start date
https://gitlab.redweb.dk/aesirx/aesir-webservice/-/commit/42d29da604ceb1decea51f39e00d45fad76dcce6 
Please help me apply for status

**Comment by CongThuong** [comment]
I just created 2 status for this task.  As you told me, we have 2 status: RUNING  - CLOSED. So please reopen the task https://gitlab.redweb.dk/aesirx/aesir-webservice/-/issues/160 Chi @NguyenTrang091296

**Comment by nhat-r-digital** [comment]
This 'status' was returned from the API ('published' parameter), using this for frontend status. Please check again a @GiaPhu811  a @toanredweb

**Comment by toanredweb** [comment]
I fixed it @nhat-r-digital

**Comment by VanTrieuThanh** [comment]
The status has showing but the item with the end date is the part still show on "Running"
![image](https://user-images.githubusercontent.com/44457418/209289778-566cd01b-2e1e-49b7-bc1e-315ab4b52b84.png)

**Comment by toanredweb** [comment]
The API returns only published field = 1 for all posts even , Pls help me check a @nhat-r-digital cc a @NguyenBao10 
![Screenshot from 2022-12-23 14-25-12](https://user-images.githubusercontent.com/70501609/209291889-e3f4154e-8fda-4fe4-a9c6-5d93b7330490.png)

**Comment by nhat-r-digital** [comment]
i fix it now, pls wait a minute

**Comment by toanredweb** [comment]
What's the status? @nhat-r-digital

**Comment by nhat-r-digital** [comment]
@toanredweb sorry, i'm late and i waiting a @NguyenBao10  review it

**Comment by nhat-r-digital** [comment]
@toanredweb it's ready, pls check

**Comment by VanTrieuThanh** [comment]
Status still Running when it expired 
![image](https://user-images.githubusercontent.com/44457418/212228038-b75d2bd7-9dde-4744-a5f4-efa647fbb589.png)

**Comment by nhat-r-digital** [comment]
Running: **status** = 1: The current date is included in the start date - end date
Stop: **status** = 0: The current date is greater than the start date
Schedule: **status** = 2: The current date is less than the start date
![image](https://user-images.githubusercontent.com/117979505/212268273-dffe0bc9-2f0b-4484-8c22-56846a3d0bc0.png)

@toanredweb @GiaPhu811  please check and get 'status' instead of get 'published'

**Comment by thaoredweb** [comment]
I reopen this issue since when I set up at local with Campaign. It show Stop status even though the start date is less than the end date
![image](https://user-images.githubusercontent.com/30283123/217477535-a6345f55-5125-4ad9-b9ac-69b23aaddd49.png)

**Comment by nhatvippro** [comment]
pls checked request data of start_date and end_date when user choosen date @toanredweb 
![image](https://user-images.githubusercontent.com/117979505/217487135-95e5ba82-e219-4760-b501-bcdfeec278bc.png)

**Comment by VanTrieuThanh** [comment]
it has update for status 
![Screenshot from 2023-02-23 15-03-39](https://user-images.githubusercontent.com/44457418/220054016-f9dc6bd0-0237-4f3e-b0e3-d846f9ad6b79.png)

But with the case create the current time 
![image](https://user-images.githubusercontent.com/44457418/220054664-ee20846d-e4a8-4e5a-826d-51b7a470e41a.png)
The Item just create is "Schedule"
![image](https://user-images.githubusercontent.com/44457418/220054938-86e7d2e7-8723-4fd1-ac1d-2457b0d53adb.png)
When I save it again the status has changed 
![image](https://user-images.githubusercontent.com/44457418/220055154-f435eed9-978f-4018-84ae-2752df8be196.png)

**Comment by toanredweb** [comment]
Pls help check the api "status"  @nhatvippro
